### ISSUE TITLE
Add file in issue

### ISSUE THREAD

**Issue by Nivetha-cloud** [TestGit-Psl/demo-repository#1]
In top right corner you will find the attachment symbol
[GitFile-1.txt](https://github.com/user-attachments/files/17202302/GitFile-1.txt)

**Comment by Nivetha-cloud** [comment]
Testing comments in the issue on oct 2024
[TextFile-8.txt](https://github.com/user-attachments/files/17209395/TextFile-8.txt)
[TextFile-7.txt](https://github.com/user-attachments/files/17209375/TextFile-7.txt)
[GitFile-4.txt](https://github.com/user-attachments/files/17209380/GitFile-4.txt)

**Comment by Nivetha-cloud** [comment]
How Uranus spins?
Ans: It spins sideways

**Comment by Nivetha-cloud** [comment]
Where is Water in space?
Ans: Water is everywhere

**Comment by Jessica192-cell** [comment]
need quick solution

**Comment by Jessica192-cell** [comment]
> need quick solution

can finish it by EOD

**Comment by Nivetha-cloud** [comment]
As the issue is resolved Hence closing
